version: '3'

services:
    solr:
      image: solr:${SOLR_VERSION}
      container_name: biotestmine-solr

      ports:
        - "${SOLR_PORT}:8983"

      volumes:
        - ./docker_context/solr:/scripts

      entrypoint:
        - docker-entrypoint.sh
        - /scripts/solr-intermine
        - ${DB_NAME}

    # The main container which is building the CHOmine
    build:
        container_name: biotestmine-build
        build:
            context: docker_context
            dockerfile: Dockerfile.chomine.build
            args:
                USERID: ${USERID}

        environment:
            - GRADLE_OPTS=-server -Xmx8g -XX:+UseParallelGC -Xms2g -XX:SoftRefLRUPolicyMSPerMB=1 -XX:MaxHeapFreeRatio=99 -Dorg.gradle.daemon=false
            - PSQL_DB_NAME=${PSQL_DB_NAME}
            - PSQL_USER=${PSQL_USER}
            - PSQL_PWD=${PSQL_PWD}
            - PGPORT=${PSQL_PORT}
            - TOMCAT_USER=${TOMCAT_USER}
            - TOMCAT_PWD=${TOMCAT_PWD}
            - DB_NAME=${DB_NAME}
            - WORDPRESS_PORT=${WORDPRESS_PORT}
        volumes:
            - ./mine/data:/home/intermine/data
            - ./mine/configs:/home/intermine/configs
            - ./mine/.intermine:/home/intermine/.intermine
            - ./mine/logs:/home/intermine/logs
            - ./mine/scripts:/home/intermine
            - ${BIO_SOURCES}:/home/intermine/mine/bio-sources

        depends_on:
            - "postgres"
            - "solr"

    # Webserver for the Intermine instance
    tomcat:
        image: tomcat:${TOMCAT_VERSION}
        container_name: biotestmine-tomcat
        #domainname: chomine.boku.ac.at
        ports:
            - "${TOMCAT_PORT}:8080"
        environment:
            - JAVA_OPTS="-Dorg.apache.el.parser.SKIP_IDENTIFIER_CHECK=true"
        volumes:
            - ./docker_context/tomcat/context.xml:/usr/local/tomcat/conf/context.xml
            - ./docker_context/tomcat/server.xml:/usr/local/tomcat/conf/server.xml
            - ./docker_context/tomcat/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
            - ./docker_context/tomcat/manager.xml:/usr/local/tomcat/conf/Catalina/localhost/manager.xml

        depends_on:
            - "postgres"

    # Database for the Intermine interactions
    postgres:
        image: postgres:${PSQL_VERSION}
        container_name: biotestmine-postgres
        ports:
            - "${PSQL_PORT}:${PSQL_PORT}"
        command: postgres -c config_file=/etc/postgresql.conf -p ${PSQL_PORT}
        volumes:
            - ./docker_context/postgres/init_postgresql.sh:/docker-entrypoint-initdb.d/init_postgresql.sh
            - ./docker_context/postgres/postgresql.conf:/etc/postgresql.conf
        environment:
            - PGPORT=${PSQL_PORT}

    # Java IDE for bio-source development
    idea:
        container_name: biotestmine-intellj
        build:
            context: docker_context
            dockerfile: Dockerfile.chomine.intellij
            args:
                USERID: ${USERID} # Must be the same as the user at host (X11-permissions)

        environment:
            - DISPLAY=:0

        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
            - ${BIO_SOURCES}:/home/developer/bio_sources

        depends_on:
            - "build"

        privileged: true

    # # RSS feed containers
    # db:
    #   container_name: biotestmine-mysql
    #   image: mysql:5.7
    #
    #   restart: always
    #   environment:
    #     - MYSQL_ROOT_PASSWORD=${MSQL_ROOT_PWD}
    #     - MYSQL_DATABASE=wordpress
    #     - MYSQL_USER=${WORDPRESS_USER}
    #     - MYSQL_PASSWORD=${WORDPRESS_USER_PWD}
    #
    # wp:
    #   container_name: biotestmine-wp
    #   depends_on:
    #     - db
    #   image: wordpress:latest
    #
    #   ports:
    #    - "${WORDPRESS_PORT}:80"
    #   restart: always
    #   environment:
    #     - WORDPRESS_DB_HOST=db:3306
    #     - WORDPRESS_DB_USER=${WORDPRESS_USER}
    #     - WORDPRESS_DB_PASSWORD=${WORDPRESS_USER_PWD}
    #     - WORDPRESS_DB_NAME=wordpress
